### ISSUE TITLE
Version 1.71.19 Used is removed from Open SAP

### ISSUE THREAD

**Issue by arunkrishnamoorthy** [SAP/ui5-flush-game#5]
The following version https://openui5.hana.ondemand.com/1.71.19/resources/sap-ui-core.js is removed from SAP. 

![image](https://user-images.githubusercontent.com/7466608/186258504-2935a6c3-3238-4e54-bf3f-2cb6be6fed61.png)

**Comment by akudev** [comment]
Hi Arun, thanks for reporting and sorry for the delay. This is fixed by https://github.com/SAP/ui5-flush-game/pull/6
